restify/clients

lib/HttpClient.js, package.json, test/nock.js
If the socket connected very quickly (e.g. to localhost), the
signRequest callback was never called.
=> Make sure signRequest is called before send

package.json
Dep | Old Version | New Version
-------- | --------- | -----------
dtrace-provider |   ^0.5.0 |  ^0.6.0
semver | ^4.3.6 |  ^5.0.1
Dep | Old Version | New Version
-------- | --------- | -----------
eslint | ^0.24.0 | ^1.3.1
jscs | ^1.13.1 | ^2.1.1
=> Update dtrace provider and other out of date deps

README.md
The documentation was using a `req` variable that is not declared. Additionally the second anonymous function definition hides the `err`, `res`, `socket`, and `head` variables.
This matches my eariler PR for the restify/node-restify repo https://github.com/restify/node-restify/pull/960
=> Fix incorrect client websocket example

lib/HttpClient.js, lib/helpers/auditor.js, package.json, test/index.js
This is the initial support for the Req/Res auditor. The user must
provide the following options and can fix #14.
* opts.audit: true | false
- This enables the default implementation provided at
lib/helpers/auditor.js
* opts.auditor: function
- This enables the user to provide his/her own auditor function.
This was heavily inspired by the node-restify's auditor plugin.
*	modified:   lib/HttpClient.js
- Requiring the new auditor
- Calling the default auditor function if the property "audit" is
provided (progagated as opts.audit.defaultEnabled)
- Calling the user-provided function (propagated as opts.audit.func).
- Adding the latency information header that is commonly used by the
community.
- Adding the "audit" property to the class, with the possible user's
options.
- Propagating the …
=> Adding support to Req/Res Auditor similar to Server.

lib/HttpClient.js, lib/StringClient.js, test/index.js
This PR is related to this suggestion: https://github.com/restify/clients/issues/19
301 and 302 redirects works like 303 - they force a GET request instead of preserving the original HTTP method unless original method is HEAD. Although this behaviour is not specified in RFC7231, almost every client works like this, so I believe it's good to keep the same behaviour. 307 redirects preserve the original HTTP method.
We just follow redirects if the followRedirects option is truthy. It's also possible to specify the maxRedirects option - which limits the number of redirects to follow. maxRedirects default value is 5. If we exceed this limit, a TooManyRedirectsError is thrown.
**Disclaimer**: HttpClient just sends a redirect event - StringClient is responsible for executing the redirect …
=> Follow redirects

.eslintrc
This fixes 'make lint' on master. Currently on master I see this:
https://gist.github.com/trentm/57ec140836355cb06a4f6307beed60ae
=> fix .eslintrc: duplicate 'comma-dangle' key

CHANGES.md, lib/HttpClient.js, lib/helpers/bunyan.js, lib/index.js, package.json, test/bunyan.js
Fixes #65
Fixes the regression from restify/node-restify#501
=> export 'bunyan.serializers', fix client constructor to ensure needed serializers

CHANGES.md, package.json
See discussion at restify/clients#42. That change introduced a backward
incompatible change without a major ver bump of restify-clients.
(Note: I did this as a PR instead of commiting directly in case there is follow-up discussion on this backout.)
=> switch back to restify-errors@3 to avoid backward incompatible change

CHANGES.md, README.md, lib/HttpClient.js, test/proxy.js
See the changelog entry (https://github.com/restify/clients/pull/85/files#diff-8b1c3fd0d4a6765c16dfd18509182f9dR5) and restify/node-restify#878 discussion for notes.
=> restify/node-restify#878 HTTP proxy improvments (`http_proxy` et al)

.travis.yml, CHANGES.md, Makefile, README.md, lib/JsonClient.js, test/index.js
@DonutEspresso @rajatkumar Adds an extra `safeStringify` option to the `JSONClient` to safely parse circular JSON.
=> add option to safely stringify circular json

lib/helpers/bunyan.js, package.json, test/index.js
node-uuid is deprecated
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
You can read more about it over https://github.com/kelektiv/node-uuid/issues/142 and https://github.com/kelektiv/node-uuid/issues/155
Thanks
=> Use uuid module instead of node-uuid

CHANGES.md, package.json, test/errors.js
Commit [aee4d807](https://github.com/restify/clients/commit/aee4d807ce75cd02fb8c4ac77ca8bc68117e4070) updated the `restify-errors` package to `^4.3.0`, which breaks the API presented by the `restify-clients` package, as discussed in restify/clients#42. This change reverts it back to an appropriate version of `restify-errors`, and adds a test to check that `err.body.code` has the correct name and other fields, to prevent future erroneous updates.
=> Revert update of restify-errors dependency

.eslintrc, lib/JsonClient.js, package.json, test/JsonClient.js, test/index.js
Related to: https://github.com/restify/clients/issues/127
We were facing issues when 'accept' header was something like: "application/vnd.trustvox-v2+json".
I think it should be possible to update both: 'accept' and 'contentType' headers as other ``StringClient`` (https://github.com/restify/clients/blob/master/lib/StringClient.js#L21)
I will also update documentation that is missing 'contentType' option.
=> Use options.accept and contentType when provided

package-lock.json, package.json
This issue (https://nodesecurity.io/advisories/mime_regular-expression-denial-of-service) was describe here https://github.com/broofa/node-mime/issues/167 and fixed from version >= 1.4.1 (More specific in this commit https://github.com/broofa/node-mime/commit/855d0c4b8b22e4a80b9401a81f2872058eae274d)
=> Update mime to v1.4.1 avoiding vulnerabilities

CHANGES.md, lib/HttpClient.js, test/HttpClient.test.js
Fixes #141 
The behavior of `url.parse` is kind of mind blowing, too.
=> Breaking: throw on missing protocol in url options

README.md, lib/HttpClient.js, test/JsonClient.test.js, test/StringClient.test.js
Went to try and fix #134 but could not repro. But added unit tests to make sure this is first class and supported moving fwd.
=> new: 'query' option in client constructor and per request options

README.md, lib/HttpClient.js, lib/helpers/timings.js, test/e2e.js, test/index.js
Measure timings:
- DNS Lookup
- TCP Connection
- TLS Handshake
- First Byte
- Content Transfer
- Total
- Should we put it behind a flag?
- What's the performance impact of calling `process.hrtime()` multiple times, is there any known?
=> feat(HttpClient): add timings to res

lib/HttpClient.js, lib/JsonClient.js, lib/helpers/errors.js, package.json, test/errors.js, test/errors.test.js, test/index.js, tools/nspBadge.js
Addresses #104. 
Here are example errors of both classes:
```
{ ConnectTimeoutError: GET request to http://169.254.1.10/foo?a=1 failed to obtain connected socket within 100ms
at buildConnectTimeoutError (/Users/aliu/Sandbox/restify-clients/lib/HttpClient.js:153:12)
at Timeout.connectTimeout [as _onTimeout] (/Users/aliu/Sandbox/restify-clients/lib/HttpClient.js:231:23)
at ontimeout (timers.js:365:14)
at tryOnTimeout (timers.js:237:5)
at Timer.listOnTimeout (timers.js:207:5)
name: 'ConnectTimeoutError',
jse_shortmsg: 'GET request to http://169.254.1.10/foo?a=1 failed to obtain connected socket within 100ms',
jse_info: { fullUrl: 'http://169.254.1.10/foo?a=1', connectTimeout: 100 },
message: 'GET request to http://169.254.1.10/foo?a=1 failed to obtain connected socket within 100ms' }
```
``` …
```
=> feat: add more context for Request/Connect/DNSTimeoutErrors

lib/JsonClient.js
Fixes #160.
Not sure how to best test this, any ideas? My guess is that connection establishment takes too long and the timeout triggers during this phase.
=> fix: handle request timeouts when a response object has not yet been created

package.json
This fixes issue #168. Would it be possible to also get a 1.5.3 release with this change? It looks like 1.5.2 came from bbdeb79442a0b79bf55a788b0a409a0b5dc9cc84, so a `1.x` branch could be made based on that.
=> dtrace-provider dependency inadvertently removed by #101

.travis.yml, README.md, lib/HttpClient.js, test/appendPath.test.js, test/e2e.js
Fixes #75 
It's unclear that the existing code ever worked as intended since `this.path` was never set. It turns out that fixing this behavior is a breaking change, so I gated it behind an option.
=> new: append to base path if one exists

lib/HttpClient.js, test/StringClient.test.js
Turn res stream readable immediately to make it possible to consume later in inherited clients.
=> fix(HttpClient): turn res stream to readable in HttpClient

lib/HttpClient.js
As part of #179 I discovered `once` was being used to enable sloppy behavior of the request lifecycle management. This PR converts all `once` wrappers of callbacks into `once.strict` to ensure proper, valid behavior. This will make further improvements more straightforward.
=> chore: opinionated clean up of once callbacks

Makefile, package.json
Got tired of seeing the red outdated badge on the README. :)
EDIT: bummer, it seems eslint@5.x is only supported by node6+. Reverting back to eslint@4.x for now.
=> chore: rev dependencies

lib/HttpClient.js
I have observed that in scenarios where the process is under heavy CPU usage, that it's possible to hit the case where the callback is called multiple times due to how work is getting scheduled. This leads me to think that it would be safer to set the flag before invoking the user provided callback, but I'm not sure how to go about testing/verifying this.
Any thoughts?
=> fix: callback getting invoked more than once causing throw 

lib/HttpClient.js, package.json, test/querystring.test.js
Restify deserializes `?foo[a]=1&foo[b]=2` into a POJO - seems restify-clients should be symmetrical and do the same on the way out.
=> feat(qs): support serializing objects into associative array params

lib/HttpClient.js, test/index.js
=> fix: ensure getMetrics and getTimings are always available

lib/HttpClient.js
Comments are fairly self explanatory. Happy to expand & discuss further.
TLDR; `HttpClient.request` is currently unavoidably throwing for a known non-actionable failure scenario in core, so we're now disregarding it.
=> Ignore IncomingMessage errors after response

lib/HttpClient.js, test/HttpClient.test.js
BREAKING CHANGE: if User-Agent is given via headers, but is not given
via options, keep the headers User-Agent instead of replacing it with
restify-clients UA. This change makes User-Agent handling more aligned
with how restify-clients deals with other headers which can be overriten
by options.
The reasoning behind this is in cases where restify-clients is acting
like a forward-proxy of sorts. If User-Agent is present in headers
there's probably a request forwarding happening.
=> chore(HttpClient): keep User-Agent on headers

.github/workflows/commitlint.yml, Makefile, commitlint.config.js, package.json
Instead of using angular's preset, use conventionalcommits preset to
ensure we're following the Conventional Commits  standard.
=> chore(package)!: use conventionalcommits preset

package.json
`yarn` respects the engine field, which makes any changes to it a
breaking change to all dependencies of `restify-clients`. The `engine`
field was originally added in this project to be informative, not a
strict restriction. Drop it to prevent unwanted breaking changes on
other packages.
=> feat: drop engine field on package.json

.github/workflows/release.yml
- change the workflow publish steps to use a npm automation token
- also run workflow on v*.x branches, allowing us to use the same
workflow to release previous majors
=> chore(ci): improve release workfow
